config/routes.rb
Rails.application.routes.draw do
  get 'urls/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :urls, only: [:index, :create, :destroy]
  get ':generated_token', to: "urls#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :generated_token, uniqueness: true, length: { minimum: 3 }
  validates :base_url, presence: true, format: { with: /\w+-*\w+(\.{1}\w+-*\w+)+(\/\w+-*\w+(\?{1}(\w+={1}.*)(&\w+={1}.*)*))*/ }

  belongs_to :user, optional: true

  class << self
    CHARACTERS = [*'a'..'z', *'A'..'Z', *'0'..'9'].freeze

    def generate_token
      token = ''
      6.times { token += CHARACTERS.sample }
      token
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true

  has_many :urls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @url = Url.new
    redirect_to urls_path if current_user
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :create, :show]

  def index
    redirect_to root_path unless current_user
    init_index
  end

  def show
    url = Url.where(generated_token: params[:generated_token]).first
    redirect_to url.base_url
  end

  def create
    @url = Url.new(url_params)
    set_token if @url.generated_token.empty?
    @url.user = current_user if current_user
    save_url
    render_appropriate_page
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy if @url.user == current_user
    redirect_to urls_path
  end

  private

  def render_appropriate_page
    if current_user
      @urls = Url.where(user: current_user).order(created_at: :desc)
      render :index
    else
      render 'pages/home' unless current_user
    end
  end

  def save_url
    if @url.save
      @saved_url = @url
      @url = Url.new
    elsif url_params[:generated_token].empty?
      @url.generated_token = nil
    end
  end

  def init_index
    @url = Url.new
    @urls = Url.where(user: current_user).order(created_at: :desc)
  end

  def set_token
    token = Url.generate_token until token && Url.where(generated_token: token).empty?
    @url.generated_token = token
  end

  def url_params
    params.require(:url).permit(:base_url, :generated_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper

  def generated_url
    saved_url_tag(@saved_url) if @saved_url
  end

  def saved_url_tag(saved_url)
    url = "#{root_url}#{saved_url.generated_token}"
    render 'pages/saved_url', url: url
  end

  def url_card_tag(url)
    short_url = "#{root_url}#{url.generated_token}"
    render 'urls/url_card', url: url, short_url: short_url
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/login_access' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_saved_url.html.erb
<div data-controller="copy-link">
  <i class="fas fa-copy" data-action="click->copy-link#copy"></i>
  <%= link_to url, url, target: "_blank", 'data-copy-link-target': 'link'%> 👉 <%= @saved_url.base_url %>
</div>

app/views/pages/_url_form.html.erb
<div class="url-form">
  <%= simple_form_for url do |f| %>
    <%= f.input :base_url, placeholder: 'Enter the url to shortened', label: false %>
    <%= f.input :generated_token, placeholder: 'enter a custom path (optional)', label: false %>
    <%= f.submit 'Shorten my URL', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Welcome to URL Shortener</h1>

<%= render 'pages/url_form', url: @url %>

<%= generated_url %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div data-controller="flashes">
    <div class="flash flash-notice" data-flashes-target='flash'>
      <%= notice %>
      <button type="button" data-action="click->flashes#dismiss">
        X
      </button>
    </div>
  </div>
<% end %>
<% if alert %>
  <div data-controller="flashes">
    <div class="flash flash-alert" data-flashes-target='flash'>
      <%= alert %>
      <button type="button" data-action="click->flashes#dismiss">
        X
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_login_access.html.erb
<div class="navbar">
  <div class="actions">
    <% if current_user %>
      <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete %>
      <%= link_to 'Saved Urls', urls_path %>
    <% else %>
      <%= link_to 'Connexion', new_user_session_path %>
      <%= link_to 'Inscription', new_user_registration_path %>
    <% end %>
</div>
</div>

app/views/urls/_url_card.html.erb
<div class='url-card'>
  <p><%= url.base_url %></p>
  <i class="fas fa-copy" data-action="click->copy-link#copy"></i>
  <%= link_to short_url, short_url, target: "_blank", 'data-copy-link-target': 'link' %>
  <%= link_to '<i class="fas fa-trash"></i>'.html_safe, url_path(url.id), method: :delete, data: { confirm: "are you sure?" } %>
</div>

app/views/urls/index.html.erb
<h1>My Urls</h1>

<%= render 'pages/url_form', url: @url %>

<div class="url-cards">
  <% @urls.each do |url| %>
    <div data-controller="copy-link">
      <%= url_card_tag url %>
    </div>
  <% end %>
</div>